export const cardDefinitions = {
  "arian.stone_breath": {
    id: "arian.stone_breath",
    name: "Stone Breath",
    classId: "arian",
    kind: "spell",
    type: "attack",
    rarity: "common",
    role: "attack",
    artKey: "stone",
    cost: 1,
    target: "enemy",
    image: null,
    text: "Deal 2 damage. Gain 1 Pressure.",
    mechanicalTags: ["damage", "pressure_gain"],
    balanceNote: "Low damage starter that begins Arian's scaling.",
    actions: [
      { type: "damage", amount: 2 },
      { type: "gainCounter", counter: "pressure", amount: 1 },
    ],
  },
  "arian.granite_skin": {
    id: "arian.granite_skin",
    name: "Granite Skin",
    classId: "arian",
    kind: "spell",
    type: "skill",
    rarity: "common",
    role: "defense",
    artKey: "armor",
    cost: 1,
    target: "self",
    image: null,
    text: "Gain 5 block.",
    mechanicalTags: ["block", "defense"],
    balanceNote: "Reliable defense for a slow deck.",
    actions: [{ type: "block", amount: 5 }],
  },
  "arian.tectonic_wait": {
    id: "arian.tectonic_wait",
    name: "Tectonic Wait",
    classId: "arian",
    kind: "spell",
    type: "power",
    rarity: "uncommon",
    role: "setup",
    artKey: "seismic",
    cost: 2,
    target: "self",
    image: null,
    text: "Gain 2 Pressure. Draw 1 card.",
    mechanicalTags: ["pressure_gain", "draw", "setup"],
    balanceNote: "Setup card that replaces itself.",
    actions: [
      { type: "gainCounter", counter: "pressure", amount: 2 },
      { type: "draw", count: 1 },
    ],
  },
  "arian.stored_impact": {
    id: "arian.stored_impact",
    name: "Stored Impact",
    classId: "arian",
    kind: "spell",
    type: "skill",
    rarity: "uncommon",
    role: "setup",
    artKey: "stone",
    cost: 2,
    target: "self",
    image: null,
    text: "Store 4 damage. Your next attack adds it.",
    mechanicalTags: ["stored_damage", "delayed_damage", "combo"],
    balanceNote: "Visible setup and risk because the damage is delayed.",
    actions: [{ type: "storeDamage", amount: 4 }],
  },
  "arian.mossbound_guardian": {
    id: "arian.mossbound_guardian",
    name: "Mossbound Guardian",
    classId: "arian",
    kind: "monster",
    type: "skill",
    rarity: "common",
    role: "summon",
    artKey: "moss",
    cost: 2,
    target: "none",
    image: null,
    text: "Summon a 2/6 Guardian with Guard.",
    mechanicalTags: ["summon", "guard", "tank"],
    balanceNote: "Defensive unit helps Arian reach payoff turns.",
    monster: { attack: 2, hp: 6, traits: ["guard"] },
  },
  "arian.seismic_pressure": {
    id: "arian.seismic_pressure",
    name: "Seismic Pressure",
    classId: "arian",
    kind: "spell",
    type: "power",
    rarity: "rare",
    role: "setup",
    artKey: "seismic",
    cost: 3,
    target: "self",
    image: null,
    text: "Gain 3 Pressure and 3 block.",
    mechanicalTags: ["pressure_gain", "block", "scaling"],
    balanceNote: "Prototype version of a persistent pressure engine.",
    actions: [
      { type: "gainCounter", counter: "pressure", amount: 3 },
      { type: "block", amount: 3 },
    ],
  },
  "arian.faultline_slam": {
    id: "arian.faultline_slam",
    name: "Faultline Slam",
    classId: "arian",
    kind: "spell",
    type: "attack",
    rarity: "rare",
    role: "payoff",
    artKey: "seismic",
    cost: 3,
    target: "enemy",
    image: null,
    text: "Deal 5 + 2 per Pressure. Remove all Pressure.",
    mechanicalTags: ["damage", "pressure_spend", "payoff"],
    balanceNote: "Main payoff card. Strong when built up, weak when rushed.",
    actions: [{ type: "damage", amount: 5, scalingCounter: "pressure", scalingAmount: 2, spendCounter: true }],
  },
  "arian.kindly_cataclysm": {
    id: "arian.kindly_cataclysm",
    name: "Kindly Cataclysm",
    classId: "arian",
    kind: "spell",
    type: "reaction",
    rarity: "rare",
    role: "defense",
    artKey: "moss",
    cost: 2,
    target: "self",
    image: null,
    text: "Gain 4 block and 2 Pressure.",
    mechanicalTags: ["reaction", "block", "pressure_gain"],
    balanceNote: "Simplified reactive identity for the prototype.",
    actions: [
      { type: "block", amount: 4 },
      { type: "gainCounter", counter: "pressure", amount: 2 },
    ],
  },
  "arian.worldbreaker_patience": {
    id: "arian.worldbreaker_patience",
    name: "Worldbreaker Patience",
    classId: "arian",
    kind: "spell",
    type: "ultimate",
    rarity: "legendary",
    role: "ultimate",
    artKey: "seismic",
    cost: 5,
    target: "enemy",
    image: null,
    text: "Deal 12. If Pressure is 5+, deal 24 and remove it.",
    mechanicalTags: ["ultimate", "massive_damage", "pressure_payoff"],
    balanceNote: "Expensive finisher requiring setup for full value.",
    actions: [
      {
        type: "damageIfCounterAtLeast",
        counter: "pressure",
        threshold: 5,
        baseAmount: 12,
        bonusAmount: 12,
        spendCounterOnBonus: true,
      },
    ],
  },

  "geert.spark_anchor": {
    id: "geert.spark_anchor",
    name: "Spark Anchor",
    classId: "geert",
    kind: "spell",
    type: "attack",
    rarity: "common",
    role: "attack",
    artKey: "magnet",
    cost: 1,
    target: "enemy",
    image: null,
    text: "Deal 2 damage. Set Polarity to Positive.",
    mechanicalTags: ["damage", "polarity_positive"],
    balanceNote: "Basic polarity enabler with modest damage.",
    actions: [
      { type: "damage", amount: 2 },
      { type: "setPolarity", value: "positive" },
    ],
  },
  "geert.repulsion_pulse": {
    id: "geert.repulsion_pulse",
    name: "Repulsion Pulse",
    classId: "geert",
    kind: "spell",
    type: "skill",
    rarity: "common",
    role: "defense",
    artKey: "magnet",
    cost: 1,
    target: "self",
    image: null,
    text: "Gain 3 block. Set Polarity to Negative.",
    mechanicalTags: ["block", "polarity_negative"],
    balanceNote: "Defensive polarity setup.",
    actions: [
      { type: "block", amount: 3 },
      { type: "setPolarity", value: "negative" },
    ],
  },
  "geert.magnetic_drone": {
    id: "geert.magnetic_drone",
    name: "Magnetic Drone",
    classId: "geert",
    kind: "monster",
    type: "skill",
    rarity: "common",
    role: "summon",
    artKey: "metal",
    cost: 2,
    target: "none",
    image: null,
    text: "Summon a 2/3 Drone. Positive: +1 attack.",
    mechanicalTags: ["summon", "polarity_bonus", "buff"],
    balanceNote: "Unit that rewards polarity setup.",
    monster: { attack: 2, hp: 3, traits: [], ifPolarity: { value: "positive", attackBonus: 1 } },
  },
  "geert.attraction_field": {
    id: "geert.attraction_field",
    name: "Attraction Field",
    classId: "geert",
    kind: "spell",
    type: "power",
    rarity: "uncommon",
    role: "combo",
    artKey: "magnet",
    cost: 2,
    target: "self",
    image: null,
    text: "Gain 2 combo charge. Negative: draw 1.",
    mechanicalTags: ["buff", "polarity_bonus", "draw"],
    balanceNote: "Prototype combo setup.",
    actions: [
      { type: "gainCounter", counter: "comboCharge", amount: 2 },
      { type: "draw", count: 1, ifPolarity: "negative" },
    ],
  },
  "geert.chain_capacitor": {
    id: "geert.chain_capacitor",
    name: "Chain Capacitor",
    classId: "geert",
    kind: "spell",
    type: "attack",
    rarity: "uncommon",
    role: "combo",
    artKey: "electric",
    cost: 2,
    target: "enemy",
    image: null,
    text: "Deal 3. If Polarity changed this turn, hit another enemy for 2.",
    mechanicalTags: ["damage", "chain_reaction", "polarity_combo"],
    balanceNote: "Rewards active polarity switching.",
    actions: [
      { type: "damage", amount: 3 },
      { type: "damageRandomEnemy", amount: 2, ifPolarityChanged: true },
    ],
  },
  "geert.overclock": {
    id: "geert.overclock",
    name: "Overclock",
    classId: "geert",
    kind: "spell",
    type: "skill",
    rarity: "rare",
    role: "draw",
    artKey: "electric",
    cost: 1,
    target: "self",
    image: null,
    text: "Draw 2 cards. Take 2 damage.",
    mechanicalTags: ["draw", "self_damage", "overclock", "risk_reward"],
    balanceNote: "Strong cycle tool with a clear health cost.",
    actions: [
      { type: "draw", count: 2 },
      { type: "selfDamage", amount: 2 },
    ],
  },
  "geert.polarity_switch": {
    id: "geert.polarity_switch",
    name: "Polarity Switch",
    classId: "geert",
    kind: "spell",
    type: "reaction",
    rarity: "uncommon",
    role: "combo",
    artKey: "magnet",
    cost: 1,
    target: "self",
    image: null,
    text: "Flip Polarity. Gain 2 block.",
    mechanicalTags: ["reaction", "polarity_change", "block", "combo"],
    balanceNote: "Small defensive tool that enables combo reliability.",
    actions: [
      { type: "flipPolarity" },
      { type: "block", amount: 2 },
    ],
  },
  "geert.scrap_colossus": {
    id: "geert.scrap_colossus",
    name: "Scrap Colossus",
    classId: "geert",
    kind: "monster",
    type: "power",
    rarity: "rare",
    role: "summon",
    artKey: "metal",
    cost: 4,
    target: "none",
    image: null,
    text: "Summon a 4/6 Construct with Guard. Positive: gain 4 block.",
    mechanicalTags: ["summon", "guard", "polarity_bonus", "block"],
    balanceNote: "Big stabilizing play for a setup-heavy deck.",
    monster: { attack: 4, hp: 6, traits: ["guard"] },
    actions: [{ type: "block", amount: 4, ifPolarity: "positive" }],
  },
  "geert.perfect_chain_reaction": {
    id: "geert.perfect_chain_reaction",
    name: "Perfect Chain Reaction",
    classId: "geert",
    kind: "spell",
    type: "ultimate",
    rarity: "legendary",
    role: "ultimate",
    artKey: "electric",
    cost: 5,
    target: "enemy",
    image: null,
    text: "Deal 15 damage. For each Polarity change this combat, deal 5 more.",
    mechanicalTags: ["ultimate", "damage", "polarity_combo", "chain_reaction"],
    balanceNote: "Generated card version: huge single-target payoff that scales with polarity changes.",
    actions: [{ type: "damage", amount: 15, scalingCounter: "polarityChanges", scalingAmount: 5 }],
  },

  "wouter.silent_arrow": {
    id: "wouter.silent_arrow",
    name: "Silent Arrow",
    classId: "wouter",
    kind: "spell",
    type: "attack",
    rarity: "common",
    role: "attack",
    artKey: "arrow",
    cost: 1,
    target: "enemy",
    image: null,
    text: "Deal 3 damage.",
    mechanicalTags: ["damage", "ranged"],
    balanceNote: "Efficient simple damage for fast turns.",
    actions: [{ type: "damage", amount: 3 }],
  },
  "wouter.veilstep": {
    id: "wouter.veilstep",
    name: "Veilstep",
    classId: "wouter",
    kind: "spell",
    type: "skill",
    rarity: "common",
    role: "evasion",
    artKey: "shadow",
    cost: 1,
    target: "self",
    image: null,
    text: "Gain Evasion 1. Draw 1 card.",
    mechanicalTags: ["evasion", "draw", "stealth"],
    balanceNote: "Core defensive cycle card.",
    actions: [
      { type: "applyStatus", status: "evasion", duration: 1, targetKinds: ["hero"] },
      { type: "draw", count: 1 },
    ],
  },
  "wouter.loot_cache": {
    id: "wouter.loot_cache",
    name: "Loot Cache",
    classId: "wouter",
    kind: "spell",
    type: "skill",
    rarity: "common",
    role: "draw",
    artKey: "relic",
    cost: 1,
    target: "self",
    image: null,
    text: "Draw 2 cards. Discard 1 card.",
    mechanicalTags: ["loot", "draw", "discard"],
    balanceNote: "Generated card version: loot filtering instead of pure card advantage.",
    actions: [
      { type: "gainCounter", counter: "loot", amount: 1 },
      { type: "draw", count: 2 },
      { type: "discardRandom", count: 1 },
    ],
  },
  "wouter.ambush_cut": {
    id: "wouter.ambush_cut",
    name: "Ambush Cut",
    classId: "wouter",
    kind: "spell",
    type: "attack",
    rarity: "uncommon",
    role: "burst",
    artKey: "blade",
    cost: 2,
    target: "enemy",
    image: null,
    text: "Deal 4 damage. If you have Evasion, deal +3.",
    mechanicalTags: ["damage", "evasion_bonus", "burst"],
    balanceNote: "Rewards proper setup without being too complex.",
    actions: [{ type: "damage", amount: 4, bonusIfHeroStatus: "evasion", bonusAmount: 3 }],
  },
  "wouter.snare_trap": {
    id: "wouter.snare_trap",
    name: "Snare Trap",
    classId: "wouter",
    kind: "spell",
    type: "reaction",
    rarity: "uncommon",
    role: "defense",
    artKey: "trap",
    cost: 1,
    target: "self",
    image: null,
    text: "The next enemy unit that attacks takes 3 damage.",
    mechanicalTags: ["reaction", "trap", "retaliation"],
    balanceNote: "Generated card version: delayed anti-unit trap.",
    actions: [{ type: "applyStatus", status: "snareTrap", duration: 1, targetKinds: ["hero"], targetOverride: "self" }],
  },
  "wouter.relic_hunter": {
    id: "wouter.relic_hunter",
    name: "Relic Hunter",
    classId: "wouter",
    kind: "monster",
    type: "skill",
    rarity: "uncommon",
    role: "summon",
    artKey: "relic",
    cost: 2,
    target: "none",
    image: null,
    text: "Summon a 3/2 Hunter. Draw 1 card.",
    mechanicalTags: ["summon", "draw", "loot"],
    balanceNote: "Tempo plus card flow, but fragile body.",
    monster: { attack: 3, hp: 2, traits: [] },
    actions: [{ type: "draw", count: 1 }],
  },
  "wouter.critical_line": {
    id: "wouter.critical_line",
    name: "Critical Line",
    classId: "wouter",
    kind: "spell",
    type: "power",
    rarity: "rare",
    role: "execute",
    artKey: "arrow",
    cost: 2,
    target: "self",
    image: null,
    text: "Your next attack deals double damage if the target has 6 or less HP.",
    mechanicalTags: ["critical", "setup", "execute"],
    balanceNote: "Generated card version: conditional execute setup.",
    actions: [{ type: "applyStatus", status: "criticalLine", duration: 1, targetKinds: ["hero"], targetOverride: "self" }],
  },
  "wouter.shadow_stag": {
    id: "wouter.shadow_stag",
    name: "Shadow Stag",
    classId: "wouter",
    kind: "monster",
    type: "skill",
    rarity: "rare",
    role: "summon",
    artKey: "beast",
    cost: 3,
    target: "none",
    image: null,
    text: "Summon a 4/4 Stag. Gain Evasion 1.",
    mechanicalTags: ["summon", "evasion", "beast"],
    balanceNote: "Midgame stabilizer with evasive identity.",
    monster: { attack: 4, hp: 4, traits: [] },
    actions: [{ type: "applyStatus", status: "evasion", duration: 1, targetKinds: ["hero"] }],
  },
  "wouter.perfect_heist": {
    id: "wouter.perfect_heist",
    name: "Perfect Heist",
    classId: "wouter",
    kind: "spell",
    type: "ultimate",
    rarity: "legendary",
    role: "ultimate",
    artKey: "relic",
    cost: 5,
    target: "enemy",
    image: null,
    text: "Deal 8 damage. Draw 2. Gain Evasion 2.",
    mechanicalTags: ["ultimate", "damage", "draw", "evasion", "loot"],
    balanceNote: "Signature tempo swing with damage, protection, and refill.",
    actions: [
      { type: "damage", amount: 8 },
      { type: "draw", count: 2 },
      { type: "applyStatus", status: "evasion", duration: 2, targetKinds: ["hero"], targetOverride: "self" },
    ],
  },

  "noah.chaos_spark": {
    id: "noah.chaos_spark",
    name: "Chaos Spark",
    classId: "noah",
    kind: "spell",
    type: "attack",
    rarity: "common",
    role: "attack",
    artKey: "chaos",
    cost: 1,
    target: "enemy",
    image: null,
    text: "Deal 1 to 5 damage.",
    mechanicalTags: ["random_damage", "chaos_roll"],
    balanceNote: "Simple random damage establishes Noah's identity.",
    actions: [{ type: "randomDamage", min: 1, max: 5 }],
  },
  "noah.burning_die": {
    id: "noah.burning_die",
    name: "Burning Die",
    classId: "noah",
    kind: "spell",
    type: "skill",
    rarity: "common",
    role: "setup",
    artKey: "dice",
    cost: 1,
    target: "self",
    image: null,
    text: "Gain 1 Instability. Draw 1 card.",
    mechanicalTags: ["instability_gain", "draw", "dice"],
    balanceNote: "Low-cost setup that replaces itself.",
    actions: [
      { type: "gainCounter", counter: "instability", amount: 1 },
      { type: "draw", count: 1 },
    ],
  },
  "noah.unstable_barrier": {
    id: "noah.unstable_barrier",
    name: "Unstable Barrier",
    classId: "noah",
    kind: "spell",
    type: "skill",
    rarity: "common",
    role: "defense",
    artKey: "void",
    cost: 1,
    target: "self",
    image: null,
    text: "Gain 6 block. Take 1 damage.",
    mechanicalTags: ["block", "self_damage", "risk_reward"],
    balanceNote: "Strong defense with a small chaos drawback.",
    actions: [
      { type: "block", amount: 6 },
      { type: "selfDamage", amount: 1 },
    ],
  },
  "noah.reality_misprint": {
    id: "noah.reality_misprint",
    name: "Reality Misprint",
    classId: "noah",
    kind: "spell",
    type: "reaction",
    rarity: "uncommon",
    role: "defense",
    artKey: "void",
    cost: 1,
    target: "self",
    image: null,
    text: "Prevent next damage. Gain 1 Instability.",
    mechanicalTags: ["reaction", "ward", "instability_gain"],
    balanceNote: "Strong protection that also fuels risk.",
    actions: [
      { type: "applyStatus", status: "ward", duration: 1, targetKinds: ["hero"] },
      { type: "gainCounter", counter: "instability", amount: 1 },
    ],
  },
  "noah.void_imp": {
    id: "noah.void_imp",
    name: "Void Imp",
    classId: "noah",
    kind: "monster",
    type: "skill",
    rarity: "common",
    role: "summon",
    artKey: "demon",
    cost: 2,
    target: "none",
    image: null,
    text: "Summon a 3/2 Imp. Take 1 damage.",
    mechanicalTags: ["summon", "self_damage", "demon"],
    balanceNote: "Efficient aggressive unit with a health cost.",
    monster: { attack: 3, hp: 2, traits: [] },
    actions: [{ type: "selfDamage", amount: 1 }],
  },
  "noah.wild_equation": {
    id: "noah.wild_equation",
    name: "Wild Equation",
    classId: "noah",
    kind: "spell",
    type: "power",
    rarity: "uncommon",
    role: "setup",
    artKey: "dice",
    cost: 2,
    target: "self",
    image: null,
    text: "Your next random damage rolls twice and keeps the higher result.",
    mechanicalTags: ["random_damage", "dice", "setup", "advantage_roll"],
    balanceNote: "Makes chaos more controllable without removing randomness.",
    actions: [{ type: "applyStatus", status: "advantageRoll", duration: 1, targetKinds: ["hero"] }],
  },
  "noah.backfire_blast": {
    id: "noah.backfire_blast",
    name: "Backfire Blast",
    classId: "noah",
    kind: "spell",
    type: "attack",
    rarity: "rare",
    role: "attack",
    artKey: "chaos",
    cost: 2,
    target: "enemy",
    image: null,
    text: "Deal 8 damage. Take 3 damage.",
    mechanicalTags: ["damage", "self_damage", "risk_reward"],
    balanceNote: "High damage for cost with meaningful health risk.",
    actions: [
      { type: "damage", amount: 8 },
      { type: "selfDamage", amount: 3 },
    ],
  },
  "noah.fractured_familiar": {
    id: "noah.fractured_familiar",
    name: "Fractured Familiar",
    classId: "noah",
    kind: "monster",
    type: "skill",
    rarity: "rare",
    role: "summon",
    artKey: "demon",
    cost: 3,
    target: "none",
    image: null,
    text: "Summon a random Familiar form.",
    mechanicalTags: ["summon", "random_unit", "chaos_roll"],
    balanceNote: "Random unit outcome is flavorful but bounded.",
    monster: {
      attack: 2,
      hp: 2,
      traits: [],
      variants: [
        { attack: 2, hp: 2, nameSuffix: "Scuttler" },
        { attack: 4, hp: 1, nameSuffix: "Ripper" },
        { attack: 1, hp: 5, nameSuffix: "Bulwark", traits: ["guard"] },
      ],
    },
  },
  "noah.unwritten_catastrophe": {
    id: "noah.unwritten_catastrophe",
    name: "Unwritten Catastrophe",
    classId: "noah",
    kind: "spell",
    type: "ultimate",
    rarity: "legendary",
    role: "ultimate",
    artKey: "dice",
    cost: 5,
    target: "self",
    image: null,
    text: "Roll 3 times. Deal random damage. May backfire.",
    mechanicalTags: ["ultimate", "random_damage", "dice", "risk_reward", "self_damage"],
    balanceNote: "Signature chaos ultimate with high ceiling and real danger.",
    actions: [{ type: "chaosCatastrophe", rolls: 3, min: 1, max: 6, selfDamageOnMax: 3 }],
  },

  "neutral.spark-coin": {
    id: "neutral.spark-coin",
    name: "Spark Coin",
    classId: "neutral",
    kind: "spell",
    type: "skill",
    rarity: "common",
    role: "tempo",
    artKey: "coin",
    cost: 0,
    target: "self",
    image: null,
    text: "Gain 1 mana this turn.",
    mechanicalTags: ["mana", "tempo"],
    balanceNote: "Second-player tempo tool.",
    actions: [{ type: "gainMana", amount: 1 }],
  },
};

export const starterDecks = {
  arian: [
    "arian.stone_breath",
    "arian.stone_breath",
    "arian.granite_skin",
    "arian.granite_skin",
    "arian.tectonic_wait",
    "arian.stored_impact",
    "arian.mossbound_guardian",
    "arian.mossbound_guardian",
    "arian.seismic_pressure",
    "arian.faultline_slam",
    "arian.faultline_slam",
    "arian.kindly_cataclysm",
    "arian.worldbreaker_patience",
    "arian.tectonic_wait",
    "arian.granite_skin",
  ],
  geert: [
    "geert.spark_anchor",
    "geert.spark_anchor",
    "geert.repulsion_pulse",
    "geert.repulsion_pulse",
    "geert.magnetic_drone",
    "geert.magnetic_drone",
    "geert.attraction_field",
    "geert.chain_capacitor",
    "geert.chain_capacitor",
    "geert.overclock",
    "geert.polarity_switch",
    "geert.polarity_switch",
    "geert.scrap_colossus",
    "geert.perfect_chain_reaction",
    "geert.attraction_field",
  ],
  wouter: [
    "wouter.silent_arrow",
    "wouter.silent_arrow",
    "wouter.veilstep",
    "wouter.veilstep",
    "wouter.loot_cache",
    "wouter.ambush_cut",
    "wouter.ambush_cut",
    "wouter.snare_trap",
    "wouter.relic_hunter",
    "wouter.relic_hunter",
    "wouter.critical_line",
    "wouter.shadow_stag",
    "wouter.perfect_heist",
    "wouter.loot_cache",
    "wouter.silent_arrow",
  ],
  noah: [
    "noah.chaos_spark",
    "noah.chaos_spark",
    "noah.burning_die",
    "noah.burning_die",
    "noah.unstable_barrier",
    "noah.reality_misprint",
    "noah.void_imp",
    "noah.void_imp",
    "noah.wild_equation",
    "noah.backfire_blast",
    "noah.backfire_blast",
    "noah.fractured_familiar",
    "noah.fractured_familiar",
    "noah.unwritten_catastrophe",
    "noah.unstable_barrier",
  ],
};

export function getCardDefinition(cardId) {
  const card = cardDefinitions[cardId];
  if (!card) {
    throw new Error(`Unknown card: ${cardId}`);
  }

  return card;
}
