export const classDefinitions = {
  rook: {
    id: "rook",
    name: "Rook, the Iron Vanguard",
    shortName: "Rook",
    role: "Defender",
    aspect: "Protection / Threat Control",
    maxHp: 42,
    summary: "A shield-heavy frontliner who can absorb punishment, taunt the monster, and turn defense into damage.",
    personality: "Steady, stubborn, and happiest when the monster is looking at him instead of an ally.",
    implemented: true,
  },
  lyra: {
    id: "lyra",
    name: "Lyra, the Ember Veil",
    shortName: "Lyra",
    role: "Striker",
    aspect: "Burst / Evasion / Marking",
    maxHp: 34,
    summary: "A fast damage dealer who marks weak points, dodges attacks, and manipulates threat with precise movement.",
    personality: "Sharp, playful, and always two steps away from where danger expected her to be.",
    implemented: true,
  },
  virex: {
    id: "virex",
    name: "Captain Virex, the Loot Fleet",
    shortName: "Virex",
    role: "Opportunist",
    aspect: "Salvage / Exposed Hits / Card Draw",
    faction: "Space Pirates",
    maxHp: 38,
    summary: "A charismatic raider who feasts on weakened prey — exposes the monster, swings harder when it's already bleeding, and salvages cards out of every plasma volley.",
    personality: "All swagger, all teeth. Treats a fight like a cargo manifest — every hit is loot waiting to be claimed.",
    implemented: true,
  },
  elyra: {
    id: "elyra",
    name: "Elyra Rootweaver, Forest Golem Architect",
    shortName: "Elyra",
    role: "Builder",
    aspect: "Block Stacking / Sustain / Compounding Wards",
    faction: "Bionic Nature Elves",
    maxHp: 36,
    summary: "An engineer-druid who grows living bulwarks across the party. Stacks block, threads heals, and compounds ward effects round over round.",
    personality: "Patient, precise, and certain that every wound the canopy takes is a wound it will outgrow.",
    implemented: true,
  },
  gorath: {
    id: "gorath",
    name: "Gorath Deepbreaker, Abyss Hunter",
    shortName: "Gorath",
    role: "Berserker",
    aspect: "Frenzy / Self-Damage Tradeoffs / Execute",
    faction: "Abyssal Orcs",
    maxHp: 46,
    summary: "A pressure-forged predator who hunts harder as he bleeds. Trades HP for damage, frenzies on low-life monsters, and crushes anything already weakened.",
    personality: "Quiet, certain, and at home in pressure that would kill anyone else. The deeper the wound, the steadier his aim.",
    implemented: true,
  },
  "storm-forge": {
    id: "storm-forge",
    name: "Storm Forge Vanguard",
    shortName: "Storm Forge",
    role: "Striker",
    aspect: "Burst / Risk-Reward / Storm Charge",
    faction: "Aetherfall — Storm Caste",
    element: "storm-charge",
    maxHp: 36,
    archetypes: ["Burst", "Risk/Reward", "Storm Charge"],
    tagline: "Aggression fuels power. Strike hard, risk higher.",
    summary: "A token-fed storm channeler who weaponizes its own threat. Stacks Storm Charge tokens to amplify every hit and surges hardest under pressure.",
    personality: "Hot-running and unhesitating. Treats overload as a feature, not a fault.",
    implemented: true,
  },
  "verdant-reach": {
    id: "verdant-reach",
    name: "Verdant Reach, Greenheart Sentinel",
    shortName: "Verdant Reach",
    role: "Sustain",
    aspect: "Healing / Threat Sink / Bio-Growth",
    faction: "Aetherfall — Greenheart Conclave",
    element: "bio-growth",
    maxHp: 44,
    archetypes: ["Healing", "Threat Sink", "Bio-Growth"],
    tagline: "Take the hit. The forest remembers.",
    summary: "A bio-growth conduit who drinks aggression and breathes it back as healing. Soaks monster attention so allies can act, and turns every wound into a Bio-Growth token.",
    personality: "Calm, rooted, almost stubbornly kind — the wall that grows back stronger the more it's struck.",
    implemented: true,
  },
  "tideflow-engineer": {
    id: "tideflow-engineer",
    name: "Tideflow Engineer",
    shortName: "Tideflow",
    role: "Support",
    aspect: "Control / Threat Move / Hydroflow",
    faction: "Aetherfall — Hydroflow Guild",
    element: "hydroflow",
    maxHp: 36,
    archetypes: ["Control", "Threat Move", "Hydroflow"],
    tagline: "Pressure flows where you steer it.",
    summary: "A current-bender who treats threat like a fluid. Redirects monster attention between allies, softens incoming heat, and lubricates every team play with Hydroflow tokens.",
    personality: "Wry, precise, always two valves ahead — happiest when somebody else is getting hit because she pointed the monster there.",
    implemented: true,
  },
};

export const selectableClasses = Object.values(classDefinitions);
