export const classDefinitions = {
  rook: {
    id: "rook",
    name: "Rook, the Iron Vanguard",
    shortName: "Rook",
    role: "Defender",
    aspect: "Protection / Threat Control",
    maxHp: 42,
    summary: "A shield-heavy frontliner who can absorb punishment, taunt the monster, and turn defense into damage.",
    personality: "Steady, stubborn, and happiest when the monster is looking at him instead of an ally.",
    implemented: true,
  },
  lyra: {
    id: "lyra",
    name: "Lyra, the Ember Veil",
    shortName: "Lyra",
    role: "Striker",
    aspect: "Burst / Evasion / Marking",
    maxHp: 34,
    summary: "A fast damage dealer who marks weak points, dodges attacks, and manipulates threat with precise movement.",
    personality: "Sharp, playful, and always two steps away from where danger expected her to be.",
    implemented: true,
  },
  virex: {
    id: "virex",
    name: "Captain Virex, the Loot Fleet",
    shortName: "Virex",
    role: "Opportunist",
    aspect: "Salvage / Exposed Hits / Card Draw",
    faction: "Space Pirates",
    maxHp: 38,
    summary: "A charismatic raider who feasts on weakened prey — exposes the monster, swings harder when it's already bleeding, and salvages cards out of every plasma volley.",
    personality: "All swagger, all teeth. Treats a fight like a cargo manifest — every hit is loot waiting to be claimed.",
    implemented: true,
  },
  elyra: {
    id: "elyra",
    name: "Elyra Rootweaver, Forest Golem Architect",
    shortName: "Elyra",
    role: "Builder",
    aspect: "Block Stacking / Sustain / Compounding Wards",
    faction: "Bionic Nature Elves",
    maxHp: 36,
    summary: "An engineer-druid who grows living bulwarks across the party. Stacks block, threads heals, and compounds ward effects round over round.",
    personality: "Patient, precise, and certain that every wound the canopy takes is a wound it will outgrow.",
    implemented: true,
  },
  gorath: {
    id: "gorath",
    name: "Gorath Deepbreaker, Abyss Hunter",
    shortName: "Gorath",
    role: "Berserker",
    aspect: "Frenzy / Self-Damage Tradeoffs / Execute",
    faction: "Abyssal Orcs",
    maxHp: 46,
    summary: "A pressure-forged predator who hunts harder as he bleeds. Trades HP for damage, frenzies on low-life monsters, and crushes anything already weakened.",
    personality: "Quiet, certain, and at home in pressure that would kill anyone else. The deeper the wound, the steadier his aim.",
    implemented: true,
  },
};

export const selectableClasses = Object.values(classDefinitions);
