export const classDefinitions = {
  arian: {
    id: "arian",
    name: "Arian, the Still Colossus",
    shortName: "Arian",
    raceId: "ancient_giant",
    raceName: "Ancient Giant / Stone Troll",
    aspect: "Accumulation",
    maxHp: 34,
    maxManaCrystals: 10,
    resourceName: "Pressure",
    summary: "Slow build-up, armor, stored damage, seismic pressure, and huge payoff attacks.",
    personality: "Gentle giant, calm but secretly enjoys chaos.",
    implemented: true,
  },
  geert: {
    id: "geert",
    name: "Geert, the Polarity Architect",
    shortName: "Geert",
    raceId: "arcane_artificer",
    raceName: "Tinkerer / Arcane Artificer",
    aspect: "Control",
    maxHp: 30,
    maxManaCrystals: 10,
    resourceName: "Polarity",
    summary: "Complex combos, buffs, magnetic control, chain reactions, and overclocking.",
    personality: "Kind-hearted inventor, smart, and fond of controlled chaos.",
    implemented: true,
  },
  wouter: {
    id: "wouter",
    name: "Wouter, the Veilstalker",
    shortName: "Wouter",
    raceId: "elf_veilstalker",
    raceName: "Elf Rogue / Forest Hunter",
    aspect: "Precision",
    maxHp: 28,
    maxManaCrystals: 10,
    resourceName: "Loot / Evasion",
    summary: "Fast plays, burst damage, evasion, loot, stealth, and precision strikes.",
    personality: "Calculating, quiet, and always hunting for loot.",
    implemented: true,
  },
  noah: {
    id: "noah",
    name: "Noah, Lord of Unwritten Chaos",
    shortName: "Noah",
    raceId: "chaos_demon",
    raceName: "Demon Sorcerer / Chaos Warlock",
    aspect: "Chaos",
    maxHp: 30,
    maxManaCrystals: 10,
    resourceName: "Instability",
    summary: "Random effects, roll damage, risk-reward, self-damage, and unstable magic.",
    personality: "Brilliant isolated madman, lord of chaos, loves risky plays.",
    implemented: true,
  },
};

export const selectableClasses = Object.values(classDefinitions);

